# Generated by Django 4.1.7 on 2023-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_blog',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'نوشته ها'},
        ),
        migrations.RemoveField(
            model_name='post_blog',
            name='my_order',
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='image',
            field=models.ImageField(default='static/post/default.jpg', upload_to='media/blog/post/', verbose_name='عکس اصلی'),
        ),
    ]
