# Generated by Django 4.1.7 on 2023-02-24 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attribute_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('unit', models.CharField(blank=True, max_length=127, null=True, verbose_name='واحد ویژگی')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی  ها',
                'ordering': ('id', 'title'),
            },
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('FK_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='shop.product_category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ('id', 'title'),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(default='static/post/default.jpg', upload_to='media/blog/post/', verbose_name='عکس اصلی')),
                ('header_img', models.ImageField(default='static/post/default.jpg', upload_to='media/blog/post/', verbose_name='عکس')),
                ('text', django_quill.fields.QuillField(blank=True, null=True, verbose_name='متن')),
                ('pin', models.BooleanField(default=False, verbose_name='پین بودن')),
                ('homeshow', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('FK_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_category', to='shop.product_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='attr_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=63, verbose_name='مقدار ویژگی')),
                ('FK_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_list_part', to='shop.attribute_product', verbose_name='نام ویژگی')),
                ('FK_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attr_part', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقدار ویژگی ها',
            },
        ),
    ]
