# Generated by Django 4.1.7 on 2023-02-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
